# V5 Pro 專業流水線配置 - 均衡版本
# 目標：Class 1 (持平) 30-40%，Class 0/2 各 30-35%
version: "5.0.1"
description: "均衡版 Triple-Barrier 配置，避免類別過度不平衡"

# 波動率設定
volatility:
  method: 'ewma'  # 'ewma', 'garch'
  halflife: 60    # EWMA 半衰期（bars）

# Triple-Barrier 參數（均衡調整：目標持平類 30-40%）
triple_barrier:
  pt_multiplier: 3.5   # 止盈倍數（適度放寬）
  sl_multiplier: 3.5   # 止損倍數（適度放寬）
  max_holding: 80      # 最大持有期（適中窗口）
  min_return: 0.001    # 最小報酬閾值（0.1% = 1 basis point）

# 樣本權重
sample_weights:
  enabled: true        # 是否啟用樣本權重
  tau: 100.0           # 時間衰減參數
  return_scaling: 10.0 # 報酬縮放係數
  balance_classes: true # 類別平衡

# 輸出設定
output:
  save_meta: true         # 保存詳細 metadata
  save_weights: true      # 保存樣本權重
  compression: 'compressed'  # NPZ 壓縮

# 資料處理參數（與 V4 相同）
data:
  aggregation_factor: 10
  seq_len: 100
  alpha: 0.002
  horizons: [1, 2, 3, 5, 10]
  trading_start: 90000
  trading_end: 133000

# 資料切分
split:
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
