# V5 Pro - 機器學習最佳化配置
# 設計理念：以 DeepLOB 模型學習為核心，優化類別可區分性
version: "5.0.2-ml-optimal"
description: "針對 DeepLOB CNN-LSTM 模型優化的 Triple-Barrier 配置"

# ===================================================================
# 設計原理
# ===================================================================
# 1. 類別分佈目標：30% / 40% / 30% (下跌/持平/上漲)
#    - 持平略多：最難學習的類別，需要更多樣本
#    - 下跌/上漲對稱：確保模型不偏向多/空
#
# 2. 閾值設計：基於台股 LOB 實證數據
#    - min_return: 0.0008 (0.08%) = 約 0.8 個 tick
#    - 比 V4 的 0.2% 更敏感，但比原始 0.01% 更嚴格
#    - 符合高頻交易「小趨勢也要捕捉」的需求
#
# 3. 邊界設計：適度寬鬆避免誤觸發
#    - 3.5σ 邊界：只有真正的趨勢才會觸發
#    - 比 2σ 寬鬆（減少噪音），比 5σ 嚴格（保留信號）
#
# 4. 時間窗口：快速決策
#    - max_holding: 60 bars = 600 個原始事件
#    - 約 30-60 秒（取決於市場活躍度）
#    - 符合高頻交易的時間尺度
# ===================================================================

# 波動率設定
volatility:
  method: 'ewma'  # EWMA 對高頻數據反應更快
  halflife: 60    # 60 bars 半衰期 ≈ 5-10 分鐘

# Triple-Barrier 參數（進階調整：目標 Class 1 約 30-40%）
triple_barrier:
  pt_multiplier: 3.0   # 止盈：3.0σ（放寬，減少提前觸發，增加到期樣本）
  sl_multiplier: 3.0   # 止損：3.0σ（對稱設計）
  max_holding: 50      # 最大持有：50 bars（適中窗口）
  min_return: 0.0008   # 閾值：0.08%（約 0.8-8 個 tick，進一步提高以增加持平比例）

# 樣本權重（幫助模型學習困難樣本）
sample_weights:
  enabled: true        # 啟用權重
  tau: 80.0            # 時間衰減（稍快，強調近期數據）
  return_scaling: 12.0 # 報酬縮放（強化大波動樣本）
  balance_classes: true # 類別平衡（自動補償不平衡）

# 輸出設定
output:
  save_meta: true         # 保存完整 metadata
  save_weights: true      # 保存樣本權重
  compression: 'compressed'  # 壓縮以節省空間

# 資料處理參數
data:
  aggregation_factor: 10  # 10 事件聚合
  seq_len: 100            # 100 timesteps（DeepLOB 標準）
  alpha: 0.002            # 保留（兼容性）
  horizons: [1, 2, 3, 5, 10]
  trading_start: 90000    # 09:00:00
  trading_end: 133000     # 13:30:00

# 資料切分（按股票隨機切分，避免分布偏移）
split:
  train_ratio: 0.7   # 70% 訓練
  val_ratio: 0.15    # 15% 驗證
  test_ratio: 0.15   # 15% 測試
  seed: 42           # 隨機種子（確保可復現性）

# ===================================================================
# 預期效果
# ===================================================================
# 類別分佈：
#   - Class 0 (下跌): 28-33%
#   - Class 1 (持平): 38-44%  ← 最多（最難學）
#   - Class 2 (上漲): 28-33%
#
# 模型學習優勢：
#   1. 足夠的持平樣本 → 學會「不交易」
#   2. 對稱的上漲/下跌 → 避免偏差
#   3. 清晰的邊界定義 → 減少標籤噪音
#   4. 樣本權重輔助 → 困難樣本加權
#
# 訓練建議：
#   - 使用 Focal Loss（應對輕微不平衡）
#   - 啟用平衡採樣器（保險）
#   - 監控 per-class F1（確保三類都學到）
# ===================================================================
