# V5 Pro - 平衡配置（最優版）⭐⭐⭐ 強烈推薦
# 目標：30%/35%/35% (下跌/持平/上漲)
version: "5.0.3-balanced-optimal"
description: "精細微調 Triple-Barrier 參數以實現最佳平衡"

# ===================================================================
# 設計原理（基於快速測試結果微調）
# ===================================================================
# 快速測試顯示：
#   - 保守版：Class 1 從 45% → 21%（調整過度 -24%）
#   - 中等版：Class 1 從 45% → 7%（調整過度 -38%）
#   - 激進版：Class 1 從 45% → -10%（完全失控）
#
# 結論：需要更溫和的調整
# 目標：Class 1 從 45% → 35%（僅需 -10%）
#
# 優化策略：
# 1. 溫和降低 min_return: 0.00215 → 0.00185 (-14%)
#    - 比保守版(-30%)更溫和，避免過度調整
#    - 0.185% ≈ 1.85 個 tick，仍然敏感但不過激
#
# 2. 溫和降低止盈/止損: 5.9σ → 5.0σ (-15%)
#    - 比保守版(-24%)更溫和
#    - 5.0σ 仍然很寬鬆，主要靠 min_return 調整
#
# 3. 小幅縮短持有期: 50 → 48 bars (-4%)
#    - 幾乎不變，保持原有窗口特性
#
# 預期效果（基於估算模型）：
#   Class 1 變化 = 0.5*(-14%) + 0.3*(-15%) + 0.2*(-4%)
#                = -7.0% - 4.5% - 0.8%
#                = -12.3%
#   - Class 1: 45% → 32.7% ✅ 接近目標 35%
#   - Class 0: 29.4% → 35.6% ✅ 接近目標 30-33%
#   - Class 2: 25.6% → 31.7% ✅ 接近目標 30-33%
# ===================================================================

# 波動率設定（保持不變）
volatility:
  method: 'ewma'
  halflife: 60

# Triple-Barrier 參數（最優微調）⭐⭐⭐
triple_barrier:
  pt_multiplier: 5.0   # 止盈：5.0σ（溫和降低 -15%）
  sl_multiplier: 5.0   # 止損：5.0σ（對稱設計）
  max_holding: 48      # 最大持有：48 bars（幾乎不變）
  min_return: 0.00185  # 閾值：0.185%（溫和降低 -14%，關鍵調整）

# 樣本權重（保持不變）
sample_weights:
  enabled: true
  tau: 80.0
  return_scaling: 12.0
  balance_classes: true

# 輸出設定（保持不變）
output:
  save_meta: true
  save_weights: true
  compression: 'compressed'

# 資料處理參數（保持不變）
data:
  aggregation_factor: 10
  seq_len: 100
  alpha: 0.002
  horizons: [1, 2, 3, 5, 10]
  trading_start: 90000
  trading_end: 133000

# 資料切分（保持不變）
split:
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  seed: 42

# ===================================================================
# 預期效果
# ===================================================================
# 類別分佈預期（基於估算模型）：
#   - Class 0 (下跌): 35-36% (↑ from 29.4%)
#   - Class 1 (持平): 32-34% (↓ from 45.0%)  ← 最接近目標 35%！
#   - Class 2 (上漲): 31-33% (↑ from 25.6%)
#
# 優勢：
#   1. ⭐⭐⭐ 最可能達成理想分佈（30%/35%/35%）
#   2. 調整溫和，避免過度修正
#   3. 保持標籤質量（不會引入過多噪音）
#   4. 符合高頻交易需求（敏感但不過激）
#
# 訓練建議：
#   - 搭配 train_v5_fix_moderate.yaml 使用
#   - 預期 Class 1 Recall 提升至 35-50%（vs 當前 11.35%）
#   - 整體 F1 應保持在 60-65%
#
# 如果實際分佈仍不理想：
#   - Class 1 仍 > 37%：降低 min_return 至 0.0017 (-21%)
#   - Class 1 < 32%：提高 min_return 至 0.0019 (-12%)
#   - 每次微調 ±0.0001 (±0.01%)，觀察變化
# ===================================================================
