# 日內波段交易配置（Intraday Swing Trading）
# 設計理念：抓住日內趨勢，每天 1-2 次交易，≥1% 利潤
version: "6.0-intraday-swing"
description: "針對日內波段交易優化的趨勢標籤配置"

# ===================================================================
# 核心設計原則
# ===================================================================
# 1. 交易頻率：每天每股 1-2 次（不是高頻的 10-20 次）
# 2. 利潤目標：≥1%（扣除手續費後仍有利潤）
# 3. 持倉時間：1-3 小時（不是幾分鐘）
# 4. 核心訴求：及時抓住趨勢（不是每個小波動都交易）
#
# 關鍵改變：
#   - 標籤方法：Triple-Barrier → 趨勢標籤
#   - 時間尺度：40 bars (4-8分鐘) → 150 bars (1.5-3小時)
#   - 利潤閾值：0.25% → 1.0%
# ===================================================================

# ===================================================================
# 標籤方法：趨勢標籤（替代 Triple-Barrier）
# ===================================================================
labeling_method: "trend_adaptive"  # 使用自適應趨勢標籤

trend_labeling:
  lookforward: 150           # 往前看 150 bars ≈ 1.5-3 小時
  vol_multiplier: 2.0        # 波動率倍數（趨勢閾值 = vol × multiplier）

  # 說明：
  #   - lookforward=150: 從當前點往前看 150 個 bar 的價格變化
  #   - vol_multiplier=2.0: 需要 2σ 的變化才算趨勢
  #   - 波動率自適應：高波動期閾值自動提高，低波動期閾值降低
  #   - 預期效果：
  #       上漲: 價格在 150 bars 內上漲 ≥ 2σ（約 0.5-2%，視波動率）
  #       下跌: 價格在 150 bars 內下跌 ≥ 2σ
  #       持平: 其他情況（小震盪、橫盤）
  #
  #   調整建議：
  #     - 想要更多交易機會 → 降低 vol_multiplier (1.5-1.8)
  #     - 想要更保守過濾 → 提高 vol_multiplier (2.5-3.0)
  #     - 想要更短持倉期 → 降低 lookforward (100-120)
  #     - 想要更長持倉期 → 提高 lookforward (200-250)

# ===================================================================
# 備選方案：Triple-Barrier 重新校準（如果需要）
# ===================================================================
# 如果您仍想使用 Triple-Barrier，請使用以下配置：
triple_barrier:
  enabled: false             # 當前關閉，使用趨勢標籤
  max_holding: 250           # 250 bars ≈ 2.5-5 小時
  min_return: 0.01           # 1% 最小利潤
  pt_multiplier: 5.0         # 5σ 止盈（讓利潤跑）
  sl_multiplier: 3.0         # 3σ 止損（控制風險，盈虧比 5:3）

  # 說明：
  #   - 非對稱設計：止盈寬（5σ），止損緊（3σ）
  #   - 目標：讓利潤跑，快速止損
  #   - 盈虧比約 1.67:1

# ===================================================================
# 跨日保護（保持不變）
# ===================================================================
respect_day_boundary: true   # 強制啟用日界線保護
ffill_quality_threshold: 0.5 # 滑窗內 ffill 占比 > 50% 則跳過

# ===================================================================
# 波動率設定（保持不變）
# ===================================================================
volatility:
  method: 'ewma'
  halflife: 60

# ===================================================================
# 標準化設定（保持不變）
# ===================================================================
normalization:
  method: 'rolling_zscore'
  window: 100
  min_periods: 20

# ===================================================================
# 樣本權重（關閉，因為趨勢標籤通常更平衡）
# ===================================================================
sample_weights:
  enabled: false
  tau: 80.0
  return_scaling: 1.0
  balance_classes: true
  use_log_scale: true

# ===================================================================
# 輸出設定
# ===================================================================
output:
  save_meta: true
  save_weights: false         # 關閉權重（趨勢標籤不需要）
  compression: 'compressed'

# ===================================================================
# 資料處理參數
# ===================================================================
data:
  aggregation_factor: 10
  seq_len: 100
  alpha: 0.002
  horizons: [1, 2, 3, 5, 10]
  trading_start: 90000
  trading_end: 133000

# ===================================================================
# 資料切分
# ===================================================================
split:
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  seed: 42

# ===================================================================
# 預期效果
# ===================================================================
# 標籤分布（預期）：
#   - Class 0 (下跌): 20-30%
#   - Class 1 (持平): 40-60%  ← 小震盪全部歸為持平
#   - Class 2 (上漲): 20-30%
#
# 交易特性：
#   - 每天交易次數: 1-3 次/股
#   - 平均持倉時間: 1-3 小時
#   - 平均利潤: ≥1% (扣除手續費後仍有利)
#   - 勝率目標: 55-65%
#
# 模型學習優勢：
#   1. 學會識別真正的趨勢
#   2. 學會在橫盤時不交易
#   3. 避免頻繁交易被手續費吃掉
#   4. 符合實際交易需求
# ===================================================================
