# V5 Pro - 平衡中性標籤配置（解決「平」標籤過少問題）
# 設計理念：增加「持平」標籤比例，改善類別不平衡
version: "5.0.4-balanced-neutral"
description: "針對 Triple-Barrier「持平」標籤過少問題的修正版配置"

# ===================================================================
# 核心修正：增加「持平」標籤比例
# ===================================================================
# 問題診斷：
#   原始邏輯：PT/SL 觸發一律標 ±1，只有「時間到 + 收益極小」才標 0
#   結果：「持平」標籤 < 10%（嚴重不平衡）
#
# 解決方案（方案 A）：
#   1. PT/SL 觸發時也檢查 min_return
#   2. 若實際收益 < min_return，視為雜訊標 0
#   3. 提高 min_return 閾值（0.15% → 0.25%）
#   4. 放寬 barrier（3.5σ → 4.0σ）
#
# 預期效果：
#   下跌：28-32%
#   持平：35-45% ← 從 <10% 提升
#   上漲：28-32%
# ===================================================================

# 防跨日污染
respect_day_boundary: true

# 波動率設定
volatility:
  method: 'ewma'
  halflife: 60

# Triple-Barrier 參數（修正版）
triple_barrier:
  pt_multiplier: 4.0      # 放寬（3.5 → 4.0），減少 PT 觸發
  sl_multiplier: 4.0      # 放寬（3.5 → 4.0），減少 SL 觸發
  max_holding: 50         # 延長（40 → 50），增加 time trigger
  min_return: 0.0025      # 提高（0.15% → 0.25%），更嚴格的「清晰度」

  # ⭐ 關鍵新增參數（需配合改進版 tb_labels_v2 使用）
  pt_sl_check_min_return: true  # PT/SL 觸發也檢查 min_return
  tie_prefer: 'zero'             # 同時觸及上下界時標為 0

  # 說明：
  #   1. pt_sl_check_min_return=true 時：
  #      - PT 觸發但 ret < 0.25% → 標 0（不是 +1）
  #      - SL 觸發但 |ret| < 0.25% → 標 0（不是 -1）
  #   2. 這會大幅增加「持平」標籤
  #   3. 符合日沖邏輯：微小波動不值得交易

# 樣本權重
sample_weights:
  enabled: true
  tau: 80.0
  return_scaling: 1.0
  balance_classes: true
  use_log_scale: true

# 輸出設定
output:
  save_meta: true
  save_weights: true
  compression: 'compressed'

# 資料處理參數
data:
  aggregation_factor: 10
  seq_len: 100
  alpha: 0.002
  horizons: [1, 2, 3, 5, 10]
  trading_start: 90000
  trading_end: 133000

# 資料切分
split:
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  seed: 42

# ===================================================================
# 使用方式
# ===================================================================
#
# 測試標籤分布：
#   python scripts/test_tb_comparison.py \
#       --config configs/config_pro_v5_balanced_neutral.yaml
#
# 生成數據（需先修改 extract_tw_stock_data_v5.py 使用 tb_labels_v2）：
#   python scripts/extract_tw_stock_data_v5.py \
#       --input-dir ./data/temp \
#       --output-dir ./data/processed_v5_balanced_neutral \
#       --config configs/config_pro_v5_balanced_neutral.yaml
#
# ===================================================================

