# ===================================================================
# DeepLOB V5 平衡數據訓練配置 - 中等版
# 數據：processed_v5_balanced (Triple-Barrier 優化後)
# 目標：Class 1 Recall > 35%，三類均衡
# ===================================================================

# ==================== 基礎配置 ====================
run:
  seed: 42

labels:
  num_classes: 3
  class_names: ["下跌", "持平", "上漲"]
  class_names_en: ["down", "stationary", "up"]
  class_ids: [0, 1, 2]
  format: "v5"

  weight_calculation:
    epsilon: 1.0e-6
    normalize: true

visualization:
  confusion_matrix:
    normalize: true
    dpi: 150
    figsize: [8, 6]
    cmap: "Blues"

# ==================== 數據配置 - 使用新的平衡數據！====================
data:
  train: "data/processed_v5_balanced/npz/stock_embedding_train.npz"
  val: "data/processed_v5_balanced/npz/stock_embedding_val.npz"
  test: "data/processed_v5_balanced/npz/stock_embedding_test.npz"
  norm_meta: "data/processed_v5_balanced/npz/normalization_meta.json"

  v5_labels: true
  y_raw_validation:
    enabled: true
    expected_values: [-1, 0, 1]

  use_sample_weights: true
  weights_normalize: "mean_to_1"
  use_stock_ids: false
  fail_on_missing_keys: true

# ==================== DataLoader 配置 ====================
dataloader:
  batch_size: 256
  num_workers: 4
  pin_memory: true

  # 啟用平衡採樣器
  balance_sampler:
    enabled: true
    strategy: "inv_freq"

# ==================== 模型配置 ====================
model:
  arch: "DeepLOB"
  input:
    shape: [100, 20]
  num_classes: 3

  # 擴大網絡容量
  conv1_filters: 32
  conv2_filters: 32
  conv3_filters: 32
  lstm_hidden_size: 48
  fc_hidden_size: 48
  dropout: 0.4

  embeddings:
    enabled: false

# ==================== 損失函數配置 ====================
loss:
  type: "ce"

  # 手動權重（針對新數據分佈 31%/42%/27%）
  class_weights: "manual"
  # 新權重設計：
  # - Class 0 (31%): 1.1 ← 略提高
  # - Class 1 (42%): 1.0 ← 基準（雖仍偏多但已改善）
  # - Class 2 (27%): 1.2 ← 提高（最少）
  manual_weights: [1.1, 1.0, 1.2]

  label_smoothing:
    global: 0.0
    flat_bonus: 0.00

# ==================== 優化器配置 ====================
optim:
  name: "adamw"
  lr: 0.00012
  weight_decay: 0.0003
  grad_clip: 0.8
  amp: false
  use_bf16: false
  betas: [0.9, 0.999]
  eps: 1.0e-8
  amsgrad: false

# ==================== 學習率調度器 ====================
sched:
  name: "cosine"
  warmup_ratio: 0.1
  eta_min: 1.0e-5

# ==================== 訓練配置 ====================
train:
  epochs: 40
  accumulate_steps: 1

  early_stop:
    metric: "val.f1_macro_unweighted"
    patience: 10
    mode: "max"

# ==================== 評估配置 ====================
eval:
  group_split:
    by_stock: true

  metrics:
    unweighted: ["acc", "f1_macro", "per_class_pr_rc", "confusion"]
    weighted: ["f1_macro", "loss"]

  breakdowns: ["reasons", "t_hit_bucket", "ret_quantile", "stock"]
  thit_buckets: [0, 5, 10, 20, 100]
  ret_quantiles: [0.8, 0.9, 0.95]

# ==================== 校準配置 ====================
calibration:
  enabled: true
  type: "temperature"
  opt_metric: "weighted_nll"
  lr: 0.01
  max_iter: 50

# ==================== 推理配置 ====================
inference:
  decision: "argmax"
  cost_matrix:
    path: null
  hold_threshold: 0.0

# ==================== 日誌配置 ====================
logging:
  dir: "logs/deeplob_v5_balanced_moderate"
  save_best_by: "val.f1_macro_unweighted"

  artifacts:
    - "model"
    - "norm_meta"
    - "label_mapping"
    - "calibration"
    - "cost_matrix"
    - "metrics_json"
    - "logs_csv"
    - "confmat_png"

  wandb:
    enabled: false

# ==================== 安全檢查 ====================
safety_checks:
  validate_label_set: true
  validate_weights: true
  validate_norm_meta: true
  print_data_summary: true

# ==================== 硬件配置 ====================
hardware:
  device: "cuda"
  num_workers: 4
  pin_memory: true
  prefetch_factor: 2
  persistent_workers: true

# ==================== 續訓配置 ====================
resume:
  enabled: false
  checkpoint_path: "checkpoints/v5_balanced/deeplob_v5_best.pth"
  load_optimizer: true

# ==================== 其他配置 ====================
misc:
  save_last: true
  output_dir: "checkpoints/v5_balanced_moderate"

# ===================================================================
# 配置說明
# ===================================================================
# 數據改進：
#   - 使用 Triple-Barrier 優化後的數據
#   - Class 分佈：31% / 42% / 27% (vs 原始 29% / 45% / 26%)
#   - Class 1 降低 3%，更接近均衡
#
# 訓練策略：
#   1. 平衡採樣器 + 手動權重（雙重保障）
#   2. 擴大網絡容量（LSTM/FC 48 units）
#   3. 降低正則化（Dropout 0.4，Weight Decay 0.0003）
#   4. 適度學習率（0.00012）
#
# 預期效果：
#   - Class 1 Recall: 11.3% → 30-45% (+165-298%)
#   - Macro F1: 30.4% → 58-68% (+91-124%)
#   - 三類 Recall 差距: < 15%
#
# 使用方法：
#   python scripts/train_deeplob_v5.py \
#       --config configs/train_v5_balanced_moderate.yaml
# ===================================================================
