# ===================================================================
# DeepLOB V5 緊急修復配置 (2025-10-18)
# 問題：學習率過低 + 過度正則化 → 模型完全學不動
# 修復：提高學習率、放寬正則化、讓模型先學起來
# ===================================================================

# ==================== 运行配置 ====================
run:
  seed: 42

# ==================== 标签配置 ====================
labels:
  num_classes: 3
  class_names: ["下跌", "持平", "上涨"]
  class_names_en: ["down", "stationary", "up"]
  class_ids: [0, 1, 2]
  format: "v5"

  weight_calculation:
    epsilon: 1.0e-6
    normalize: true

# ==================== 可视化配置 ====================
visualization:
  confusion_matrix:
    normalize: true
    dpi: 150
    figsize: [8, 6]
    cmap: "Blues"

# ==================== 数据配置 ====================
data:
  train: "data/processed_v5/npz/stock_embedding_train.npz"
  val: "data/processed_v5/npz/stock_embedding_val.npz"
  test: "data/processed_v5/npz/stock_embedding_test.npz"
  norm_meta: "data/processed_v5/npz/normalization_meta.json"

  v5_labels: true
  y_raw_validation:
    enabled: true
    expected_values: [-1, 0, 1]

  use_sample_weights: true
  weights_normalize: "mean_to_1"
  use_stock_ids: false
  fail_on_missing_keys: true

# ==================== DataLoader 配置 ====================
dataloader:
  batch_size: 256  # 維持 256
  num_workers: 4
  pin_memory: true

  balance_sampler:
    enabled: false
    strategy: "inv_freq"

# ==================== 模型配置 ====================
model:
  arch: "DeepLOB"
  input:
    shape: [100, 20]
  num_classes: 3

  # DeepLOB 架構參數（維持原樣）
  conv1_filters: 32
  conv2_filters: 32
  conv3_filters: 32
  lstm_hidden_size: 48
  fc_hidden_size: 48
  dropout: 0.3  # ✅ 修復：0.5 → 0.3（降低正則化強度）

  embeddings:
    enabled: false
    num_stocks: 367
    dim: 16
    dropout: 0.1
    weight_decay: 0.0001
    max_norm: null
    unk_strategy: "explicit_unk"
    feature_dropout:
      p: 0.3
    conditioning: "film"

# ==================== 损失函数配置 ====================
loss:
  type: "ce"
  class_weights: "auto"  # 維持自動平衡
  label_smoothing:
    global: 0.05  # ✅ 修復：0.1 → 0.05（降低平滑強度）
    flat_bonus: 0.00

# ==================== 优化器配置 ====================
optim:
  name: "adamw"
  lr: 0.0003  # ✅ 關鍵修復：0.00001 → 0.0003（提高 30 倍！）
  weight_decay: 0.0001  # ✅ 修復：0.001 → 0.0001（降低 10 倍）
  grad_clip: 2.0  # ✅ 修復：0.5 → 2.0（放寬裁剪，允許更大梯度）
  amp: true
  use_bf16: true

  betas: [0.9, 0.999]
  eps: 1.0e-8
  amsgrad: false

# ==================== 学习率调度器 ====================
sched:
  name: "cosine"
  warmup_ratio: 0.1  # ✅ 修復：0.05 → 0.1（延長 warmup，穩定初期訓練）
  eta_min: 1.0e-5  # ✅ 修復：1e-6 → 1e-5（提高最低學習率）

# ==================== 训练配置 ====================
train:
  epochs: 30
  accumulate_steps: 1

  early_stop:
    metric: "val.f1_macro_weighted"
    patience: 10  # ✅ 修復：5 → 10（給模型更多機會）
    mode: "max"

# ==================== 评估配置 ====================
eval:
  group_split:
    by_stock: true

  metrics:
    unweighted: ["acc", "f1_macro", "per_class_pr_rc", "confusion"]
    weighted: ["f1_macro", "loss"]

  breakdowns: ["reasons", "t_hit_bucket", "ret_quantile", "stock"]
  thit_buckets: [0, 5, 10, 20, 100]
  ret_quantiles: [0.8, 0.9, 0.95]

# ==================== 校准配置 ====================
calibration:
  enabled: true
  type: "temperature"
  opt_metric: "weighted_nll"
  lr: 0.01
  max_iter: 50

# ==================== 推理配置 ====================
inference:
  decision: "argmax"
  cost_matrix:
    path: null
  hold_threshold: 0.0

# ==================== 日志配置 ====================
logging:
  dir: "logs/deeplob_v5_emergency_fix"  # ✅ 新目錄避免混淆
  save_best_by: "val.f1_macro_weighted"

  artifacts:
    - "model"
    - "norm_meta"
    - "label_mapping"
    - "calibration"
    - "cost_matrix"
    - "metrics_json"
    - "logs_csv"
    - "confmat_png"

  wandb:
    enabled: false
    project: "deeplob-v5-emergency-fix"
    entity: null

# ==================== 安全检查 ====================
safety_checks:
  validate_label_set: true
  validate_weights: true
  validate_norm_meta: true
  print_data_summary: true

# ==================== 硬件配置 ====================
hardware:
  device: "cuda"
  num_workers: 4
  pin_memory: true
  prefetch_factor: 2
  persistent_workers: true

# ==================== 續訓配置 ====================
resume:
  enabled: false
  checkpoint_path: "checkpoints/v5_emergency_fix/deeplob_v5_best.pth"
  load_optimizer: true

# ==================== 其他配置 ====================
misc:
  save_last: true
  output_dir: "checkpoints/v5_emergency_fix"

# ===================================================================
# 修復說明
# ===================================================================
# 1. 學習率：0.00001 → 0.0003 (提高 30 倍) ✅ 關鍵！
# 2. Weight Decay：0.001 → 0.0001 (降低 10 倍)
# 3. Grad Clip：0.5 → 2.0 (放寬 4 倍)
# 4. Dropout：0.5 → 0.3 (降低正則化)
# 5. Label Smoothing：0.1 → 0.05 (降低平滑)
# 6. Warmup Ratio：0.05 → 0.1 (延長穩定期)
# 7. Early Stop Patience：5 → 10 (給更多機會)
#
# 預期效果：
# - Epoch 1-3：Val Acc 應快速上升至 40-50%
# - Epoch 5：Val Acc 應達 60%+
# - Epoch 10：Val F1 (Weighted) 應達 0.65+
# ===================================================================
