# ===================================================================
# DeepLOB V7 實驗 2：進一步降低學習率
# 目標：解決實驗 1 的 Epoch 7-9 過擬合加劇問題
# 核心策略：更低學習率 + 更強正則化 + 嚴格早停
# 日期：2025-10-25
# V7 實驗 1 成果：Val Acc 50.18% (Epoch 7)，但 Epoch 8-9 過擬合
# ===================================================================

# ==================== 運行配置 ====================
run:
  seed: 42

# ==================== 標籤配置 ====================
labels:
  num_classes: 3
  class_names: ["下跌", "持平", "上漲"]
  class_names_en: ["down", "stationary", "up"]
  class_ids: [0, 1, 2]
  format: "v5"

  weight_calculation:
    epsilon: 1.0e-6
    normalize: true

# ==================== 可視化配置 ====================
visualization:
  confusion_matrix:
    normalize: true
    dpi: 150
    figsize: [8, 6]
    cmap: "Blues"

# ==================== 數據配置 ====================
data:
  train: "data/processed_v7/npz/stock_embedding_train.npz"
  val: "data/processed_v7/npz/stock_embedding_val.npz"
  test: "data/processed_v7/npz/stock_embedding_test.npz"
  norm_meta: "data/processed_v7/npz/normalization_meta.json"

  v5_labels: true

  y_raw_validation:
    enabled: true
    expected_values: [-1, 0, 1]

  # V7 實驗 1: 保持關閉樣本權重
  use_sample_weights: false
  weights_normalize: "mean_to_1"

  use_stock_ids: false
  fail_on_missing_keys: true

# ==================== DataLoader 配置 ====================
dataloader:
  # V7 實驗 2: 進一步減小 Batch Size (更頻繁正則化效果)
  batch_size: 128  # 實驗1: 256 → 128 (再降 50%, 梯度噪音更大防過擬合)
  num_workers: 12
  pin_memory: true

  # 關閉平衡採樣器
  balance_sampler:
    enabled: false
    strategy: "inv_freq"

# ==================== 模型配置 ====================
model:
  arch: "DeepLOB"

  input:
    shape: [100, 20]

  num_classes: 3

  # V7 實驗 1: 減小模型容量 (降低過擬合風險)
  conv1_filters: 32  # 48 → 32 (降回基準)
  conv2_filters: 32  # 48 → 32
  conv3_filters: 32  # 48 → 32

  # V7 實驗 1: 減小 LSTM/FC 容量
  lstm_hidden_size: 48  # 64 → 48 (介於 32-64)
  fc_hidden_size: 48    # 64 → 48

  # V7 實驗 2: 極限 Dropout (最大正則化)
  dropout: 0.80  # 實驗1: 0.75 → 0.80 (接近極限, 防止記憶數據)

  embeddings:
    enabled: false
    num_stocks: 367
    dim: 16
    dropout: 0.1
    weight_decay: 0.0001
    max_norm: null
    unk_strategy: "explicit_unk"
    feature_dropout:
      p: 0.3
    conditioning: "film"

# ==================== 損失函數配置 ====================
loss:
  type: "ce"

  # V7 實驗 1: 保持關閉類別權重
  class_weights: none

  # V7 實驗 2: 極限標籤平滑
  label_smoothing:
    global: 0.03  # 實驗1: 0.02 → 0.03 (防止過度自信)
    flat_bonus: 0.00

# ==================== 優化器配置 ====================
optim:
  name: "adamw"

  # V7 實驗 2: 極低學習率 (超慢學習) ⭐⭐⭐ 核心修改
  # 實驗1 梯度仍達 4.46, 說明學習率仍偏高
  lr: 0.0000007  # 實驗1: 1e-6 → 7e-7 (-30%, 接近極限)

  # V7 實驗 2: 極限 Weight Decay ⭐⭐⭐ 核心修改
  weight_decay: 0.003  # 實驗1: 0.002 → 0.003 (+50%, L2 懲罰更重)

  # V7 實驗 2: 收緊梯度裁剪 (配合低 LR)
  grad_clip: 1.5  # 實驗1: 2.0 → 1.5 (梯度達 4.46 需控制)

  amp: false
  use_bf16: false

  betas: [0.9, 0.999]
  eps: 1.0e-8
  amsgrad: false

# ==================== 學習率調度器 ====================
sched:
  name: "cosine"

  # V7 實驗 2: 大幅延長 Warmup (極平滑學習率上升)
  warmup_ratio: 0.40  # 實驗1: 0.30 → 0.40 (6/15 epochs, 前 40% 都在 warmup)
  warmup_start_factor: 0.15  # 實驗1: 0.2 → 0.15 (起點更低: 1e-7)

  # V7 實驗 2: 極低最小學習率
  eta_min: 0.0000002  # 實驗1: 3e-7 → 2e-7 (配合 7e-7 基礎 LR)

# ==================== 訓練配置 ====================
train:
  # V7 實驗 2: 延長訓練期 (LR 更低, 需要更多 epochs)
  epochs: 20  # 實驗1: 15 → 20 (超慢學習需更長時間)
  accumulate_steps: 1

  # V7 實驗 2: 保持激進早停但稍微放寬 ⭐ 核心修改
  # 實驗1 在 Epoch 7-8 達最佳, patience=1 可能太早停
  early_stop:
    metric: "val.f1_macro_weighted"
    patience: 2  # 實驗1: 1 → 2 (給 2 次機會觀察)
    mode: "max"
    min_delta: 0.0003  # 實驗1: 0.0005 → 0.0003 (稍微放寬)

# ==================== 評估配置 ====================
eval:
  group_split:
    by_stock: true

  metrics:
    unweighted: ["acc", "f1_macro", "per_class_pr_rc", "confusion"]
    weighted: ["f1_macro", "loss"]

  breakdowns: ["reasons", "t_hit_bucket", "ret_quantile", "stock"]
  thit_buckets: [0, 5, 10, 20, 100]
  ret_quantiles: [0.8, 0.9, 0.95]

# ==================== 校準配置 ====================
calibration:
  enabled: true
  type: "temperature"
  opt_metric: "weighted_nll"
  lr: 0.01
  max_iter: 50

# ==================== 推理配置 ====================
inference:
  decision: "argmax"
  cost_matrix:
    path: null
  hold_threshold: 0.0

# ==================== 日誌配置 ====================
logging:
  dir: "logs/deeplob_v7_exp2"
  save_best_by: "val.f1_macro_weighted"

  artifacts:
    - "model"
    - "norm_meta"
    - "label_mapping"
    - "calibration"
    - "cost_matrix"
    - "metrics_json"
    - "logs_csv"
    - "confmat_png"

  wandb:
    enabled: false
    project: "deeplob-v7-exp2"
    entity: null

# ==================== 安全檢查 ====================
safety_checks:
  validate_label_set: true
  validate_weights: true
  validate_norm_meta: true
  print_data_summary: true

# ==================== 硬體配置 ====================
hardware:
  device: "cuda"
  num_workers: 12
  pin_memory: true
  prefetch_factor: 4
  persistent_workers: true
  enable_tf32: true

# ==================== 續訓配置 ====================
resume:
  enabled: false
  checkpoint_path: "checkpoints/v5/deeplob_v5_best.pth"
  load_optimizer: true

# ==================== 其他配置 ====================
misc:
  save_last: true
  output_dir: "checkpoints/v5"

# ===================================================================
# V7 實驗 2 修改總結 (基於實驗 1 結果)
# ===================================================================
# 實驗 1 成果: Val Acc 50.18% (Epoch 7), Val F1 0.4949 (Epoch 8)
# 實驗 1 問題: Epoch 7-9 過擬合加劇 (Gap 1.23% → 4.32%)
#
# 修改策略：更低學習率 + 極限正則化 + 延長訓練
#
# 核心改動 (基於實驗 1, 10 個參數)：
# 1. batch_size: 256 → 128 (-50%, 更強正則化噪音) ⭐
# 2. dropout: 0.75 → 0.80 (+7%, 接近極限)
# 3. label_smoothing: 0.02 → 0.03 (+50%)
# 4. lr: 1e-6 → 7e-7 (-30%, 超慢學習) ⭐⭐⭐ 核心
# 5. weight_decay: 0.002 → 0.003 (+50%, 極限 L2) ⭐⭐⭐ 核心
# 6. grad_clip: 2.0 → 1.5 (-25%, 梯度達 4.46 需控制)
# 7. warmup_ratio: 0.30 → 0.40 (+33%, 前 6/15 epochs warmup)
# 8. warmup_start_factor: 0.2 → 0.15 (-25%, 起點 1e-7)
# 9. eta_min: 3e-7 → 2e-7 (-33%)
# 10. epochs: 15 → 20, patience: 1 → 2 (超慢需更長時間)
#
# 實驗 1 vs 實驗 0 對比:
# - Val Acc: 50.09% → 50.18% (+0.09%)
# - Val F1: 0.4871 → 0.4949 (+0.0078)
# - 最佳 Epoch: 3 → 7-8 (延後 4-5 epochs)
# - Train-Val Gap: 11.30% → 4.32% (-6.98%)
#
# 預期效果 (實驗 2):
# - Epoch 8-12 達最佳 (vs 實驗1 Epoch 7-8)
# - Val Acc > 50.5% (vs 實驗1 50.18%)
# - Train-Val Gap < 3% (vs 實驗1 4.32%)
# - 梯度 < 3.5 (vs 實驗1 4.46)
#
# 訓練指令：
# conda activate deeplob-pro
# python scripts/train_deeplob_v5.py --config configs/train_v5.yaml
# ===================================================================
